extends:
  - '@openreachtech'
ignorePatterns:
  - trials
rules:
  openreachtech/indent-in-infix-expression: off
  jsdoc/sort-tags: off
  jsdoc/check-indentation: off
  no-multiple-empty-lines: off
  arrow-parens: off
  object-curly-spacing: off
  no-multi-spaces: off
  jest/valid-title: off
  jsdoc/check-types: off
  jsdoc/check-tag-names: off
  prefer-destructuring: off
  jsdoc/check-line-alignment: off
  consistent-return: off
